# Generated by Django 5.0.2 on 2024-03-24 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ends_on',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='service',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='starts_from',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
