# Generated by Django 5.0.2 on 2024-03-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_equipments_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('user_phone', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('appointment_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
