# Generated by Django 5.0.2 on 2024-03-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reminder',
        ),
    ]
