# Generated by Django 5.0.2 on 2024-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_appointment_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='trainer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
