# Generated by Django 5.0.3 on 2024-04-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_payment'),
        ('authapp', '0016_faq'),
    ]

    operations = [
    ]
