# Generated by Django 5.0.3 on 2024-04-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_merge_0014_payment_0016_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='ans',
        ),
    ]
