# Generated by Django 5.0.3 on 2024-04-14 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_notify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notify',
            new_name='NotifUserStatus',
        ),
    ]
