# Generated by Django 5.0.3 on 2024-04-14 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_rename_notify_notifuserstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifUserStatus',
            new_name='Notify',
        ),
    ]
