# Generated by Django 5.0.3 on 2024-04-19 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_notification_remove_notify_read_by_trainer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='quest',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
